### ISSUE TITLE
`sharp` not able to install binaries on vercel

### ISSUE THREAD

**Issue by patheticGeek** [rumaan/astro-vercel-og#1]
Hi i am trying to do something similar and i am getting shrap error that it wasnt installed with correct binaries
i want to know if you have a custom install command or vercel or something for that?
i'll attach my repo and link in a bit here.

**Comment by patheticGeek** [comment]
using ver vercel is testing on from [here](https://github.com/vercel/vercel/blob/main/packages/node/test/fixtures/30-sharp/package.json)
ig the latest ver is not always supported

**Comment by rumaan** [comment]
Sorry for late reply. I'm not entirely sure on what sharp version works here though. Looks like you figured it out 👍🏻
